### ISSUE TITLE
podman.from_env() not working

### ISSUE THREAD

**Issue by josecastillolema** [containers/podman-py#223]
Everytime I try **podman.from_env()** I get this error:
```
>>> import podman
>>> podman.from_env()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 131, in from_env
    max_pool_size=max_pool_size,
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 76, in __init__
    self.api = APIClient(**api_kwargs)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 116, in __init__
    self.base_url = self._normalize_url(base_url)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 159, in _normalize_url
    f"The scheme '{uri.scheme}' must be one of {APIClient.supported_schemes}"
ValueError: The scheme 'b''' must be one of ('unix', 'http+unix', 'ssh', 'http+ssh', 'tcp', 'http')
```

Have tried CentOS 8 stream with a native podman setup and MacOS with podman machine.

Are they any pre-reqs to be able to use **podman.from_env()** ?

Thanks

CentOS Stream release 8:
```
$ podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Wed Sep 21 13:15:04 2022
OS/Arch:      linux/amd64
```

MacOS:
```
% podman version
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.19
Git Commit:   ad42af94903ce4f3c3cd0693e4e17e4286bf094b
Built:        Wed Oct 19 15:33:33 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 16:01:27 2022
OS/Arch:      linux/amd64
```

**Comment by cjw296** [comment]
Same...

**Comment by bdherouville** [comment]
This works. Be sure to activate podman.socket services :
sudo systemctl enable  podman.socket
sudo systemctl start  podman.socket

podman_client = podman.PodmanClient(base_url="http+unix:///var/run/podman/podman.sock")

**Comment by cjw296** [comment]
@bdherouville - it really doesn't. I've had better experience connecting to podman using the docker Python library than this one, which is pretty disappointing.

**Comment by jwhonce** [comment]
@josecastillolema From the stack trace line ` ValueError: The scheme 'b''' must be one of ('unix', 'http+unix', 'ssh', 'http+ssh', 'tcp', 'http')` it appears neither CONTAINER_HOST or DOCKER_HOST is in your environment.

**Comment by josecastillolema** [comment]
@bdherouville I dont think the provided workaround works:
```
$ sudo systemctl enable podman.socket
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.

$ sudo systemctl start podman.socket

$ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

$ python3
Python 3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import podman
>>> podman.from_env()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 131, in from_env
    max_pool_size=max_pool_size,
  File "/usr/local/lib/python3.6/site-packages/podman/client.py", line 76, in __init__
    self.api = APIClient(**api_kwargs)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 116, in __init__
    self.base_url = self._normalize_url(base_url)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 159, in _normalize_url
    f"The scheme '{uri.scheme}' must be one of {APIClient.supported_schemes}"
ValueError: The scheme 'b''' must be one of ('unix', 'http+unix', 'ssh', 'http+ssh', 'tcp', 'http')
```

**Comment by josecastillolema** [comment]
Hi @jwhonce ,
neither CONTAINER_HOST nor DOCKER_HOST are defined in my environment:
```
$ env | grep CONTAINER_HOST
$ env | grep DOCKER_HOST
```

Should they be?
I installed podman via: `sudo dnf install -y podman`

**Comment by josecastillolema** [comment]
@bdherouville 
```
$ python3

>>> import podman

>>> client = podman.PodmanClient(base_url="http+unix:///var/run/podman/podman.sock")

>>> client
<podman.client.PodmanClient object at 0x7f2ed2196438>

>>> client.images.list()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 43, in connect
    super().connect(netloc)
PermissionError: [Errno 13] Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
podman.errors.exceptions.APIError: Unable to make connection to UDS '/var/run/podman/podman.sock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
urllib3.exceptions.ProtocolError: ('Connection aborted.', APIError("Unable to make connection to UDS '/var/run/podman/podman.sock'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 411, in _request
    **timeout_kw,
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', APIError("Unable to make connection to UDS '/var/run/podman/podman.sock'",))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/domain/images_manager.py", line 56, in list
    response = self.client.get("/images/json", params=params)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 243, in get
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 415, in _request
    raise APIError(uri.geturl(), explanation=f"{method.upper()} operation failed") from e
podman.errors.exceptions.APIError: http://%2Fvar%2Frun%2Fpodman%2Fpodman.sock/v4.3.0/libpod/images/json (GET operation failed)
```

**Comment by jwhonce** [comment]
> Hi @jwhonce , neither CONTAINER_HOST nor DOCKER_HOST are defined in my environment:
> 
> ```
> $ env | grep CONTAINER_HOST
> $ env | grep DOCKER_HOST
> ```
> 
> Should they be? I installed podman via: `sudo dnf install -y podman`

Those environment variables are interchangeable and one or the other is required when using `.from_env()` to determine where the podman service is running.

**Comment by rhatdan** [comment]
Should podman-py just look for them in the standard location if they are not running?

**Comment by josecastillolema** [comment]
@rhatdan the rootless podman service does not work either:
```
$ systemctl --user start podman.socket
$ python3 
Python 3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import podman
>>> client = podman.PodmanClient(base_url="http+unix:///var/run/podman/podman.sock")
>>> client
<podman.client.PodmanClient object at 0x7f6d6a7c1400>
>>> client.images.list()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 43, in connect
    super().connect(netloc)
PermissionError: [Errno 13] Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
podman.errors.exceptions.APIError: Unable to make connection to UDS '/var/run/podman/podman.sock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
urllib3.exceptions.ProtocolError: ('Connection aborted.', APIError("Unable to make connection to UDS '/var/run/podman/podman.sock'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 411, in _request
    **timeout_kw,
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', APIError("Unable to make connection to UDS '/var/run/podman/podman.sock'",))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/domain/images_manager.py", line 56, in list
    response = self.client.get("/images/json", params=params)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 243, in get
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 415, in _request
    raise APIError(uri.geturl(), explanation=f"{method.upper()} operation failed") from e
podman.errors.exceptions.APIError: http://%2Fvar%2Frun%2Fpodman%2Fpodman.sock/v4.3.0/libpod/images/json (GET operation failed)
```

**Comment by josecastillolema** [comment]
@jwhonce so I guess the question is, who is responsible for defining this variables and why are not defined in my environments?
Is it a user responsibility or should they be handled as part of podman installation?

**Comment by rhatdan** [comment]
You should not specify the base_url
base_url="http+unix:///var/run/podman/podman.sock

This is the path for the rootful socket. look at the example below.  python-podman does the right thing.

```
$ python
Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 13.0.1 20230208 (Red Hat 13.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import podman
>>> client = podman.PodmanClient()
>>> client.images.list()
[<Image: 'quay.io/libpod/testimage:20221018'>, <Image: 'registry.access.redhat.com/ubi9:latest'>, <Image: 'docker.io/library/golang:1.17'>]
```

**Comment by josecastillolema** [comment]
@rhatdan :
```
$ python3
Python 3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import podman
>>> client = podman.PodmanClient()
>>> client.images.list()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 43, in connect
    super().connect(netloc)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
podman.errors.exceptions.APIError: Unable to make connection to UDS '/run/user/503/podman/podman.sock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 88, in connect
    sock.connect()
  File "/usr/local/lib/python3.6/site-packages/podman/api/uds.py", line 45, in connect
    raise APIError(f"Unable to make connection to UDS '{netloc}'") from e
urllib3.exceptions.ProtocolError: ('Connection aborted.', APIError("Unable to make connection to UDS '/run/user/503/podman/podman.sock'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 411, in _request
    **timeout_kw,
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', APIError("Unable to make connection to UDS '/run/user/503/podman/podman.sock'",))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/podman/domain/images_manager.py", line 56, in list
    response = self.client.get("/images/json", params=params)
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 243, in get
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/podman/api/client.py", line 415, in _request
    raise APIError(uri.geturl(), explanation=f"{method.upper()} operation failed") from e
podman.errors.exceptions.APIError: http://%2Frun%2Fuser%2F503%2Fpodman%2Fpodman.sock/v4.3.0/libpod/images/json (GET operation failed)
```

**Comment by rhatdan** [comment]
Is your podman.service running?  And listening on `/run/user/503/podman/podman.sock`?

If you do `podman --remote version` does it also blow up?
