### ISSUE TITLE
urllib3 version incompatibility

### ISSUE THREAD

**Issue by DilemmaRabbit** [containers/podman-py#267]
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from podman import PodmanClient
>>> uri = "unix:///run/podman/podman.sock"
>>> with PodmanClient(base_url=uri) as client:
...     version = client.version()
...     print("Release: ", version["Version"])
...     print("Compatible API: ", version["ApiVersion"])
...     print("Podman API: ", version["Components"][0]["Details"]["APIVersion"], "\n")
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.8/dist-packages/podman/client.py", line 205, in version
    return self.system.version(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/podman/domain/system.py", line 86, in version
    response = self.client.get("/version")
  File "/usr/local/lib/python3.8/dist-packages/podman/api/client.py", line 236, in get
    return self._request(
  File "/usr/local/lib/python3.8/dist-packages/podman/api/client.py", line 404, in _request
    self.request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'
>>> 
```

Error: request() got an unexpected keyword argument 'chunked'.
docker-py have same issue. [docker/docker-py#3113](https://github.com/docker/docker-py/issues/3113) 
I tried to install urllib3==1.26.5 to fix this.

problem version
urllib3==2.0.2
requests==2.30.0

**Comment by nicolargo** [comment]
Same kind of issue for the Glances project: https://github.com/nicolargo/glances/issues/2392

I found this patch done to solve the same kind of error on the Docker-Py lib: https://github.com/docker/docker-py/pull/3117

**Comment by jnatschev** [comment]
i can confirm that removing urllib3==2.0.2 and installing urllib3==1.26.5 has resolved the python exception i experienced.

**Comment by cevich** [comment]
FWIW: I found a [PR merged w/ failing CI tests](https://github.com/containers/podman-py/pull/265) that caused this.  I'm trying to fix it in my F38 CI VM update pr here: https://github.com/containers/podman-py/pull/270 but one CI test is failing and I don't know how to fix :cry:
