### ISSUE TITLE
standard proxy env var break connecting to UNIX Domain Socket

### ISSUE THREAD

**Issue by eighthave** [containers/podman-py#390]
If a standard proxy environment variable is set, then using a `unix:///` fails with an odd error:

```console
 ~ $ echo $HTTP_PROXY 
http://localhost:8081
 ~ $ python3.11 ./DemonstratePodmanClient.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hans/./DemonstratePodmanClient.py", line 12, in <module>
    version = client.version()
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/podman/client.py", line 205, in version
    return self.system.version(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/podman/domain/system.py", line 87, in version
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/podman/api/client.py", line 55, in raise_for_status
    body = self.json()
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 ~ $ unset HTTP_PROXY 
 ~ $ python3.11 ./DemonstratePodmanClient.py 
Release:  4.3.1
Compatible API:  1.41
Podman API:  4.3.1 
```

I think this is because _requests_ automatically uses the standard proxy env vars, and therefore, _requests_ is setting up an HTTP proxy, which will block the connection to the UNIX Domain Socket.

**Comment by eighthave** [comment]
One workaround is to set `export NO_PROXY='*'`
